spring:
  boot:
    admin:
      client:
        metadata:
          user:
            name: admin
            password: admin
      monitor:
        period: 60000
      discovery:
        enabled: true
      notify:
        mail:
          to: 1186817894@qq.com
          from: tantao1211@qq.com
      turbine:
        clusters: default
        location: paascloud-monitor
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false

turbine:
  app-config: paascloud-gateway #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称
